NAME    = bison
VERSION = 3.8.2
FILE    = $(NAME)-$(VERSION).tar.xz
HASH    = 9bba0214ccf7f1079c5d59210045227bcf619519840ebfa80cd3849cff5a5bf2
DIR     = $(NAME)-$(VERSION)
URL     = $(GNU_MIRROR_URL)/$(NAME)/$(FILE)

CONFIG_SUB = build-aux/config.sub

include $(MAKEDIR)/ext_tar.mk
