#ifndef LIBASM_RISCV_H
#define LIBASM_RISCV_H

#include <stddef.h>
#include <stdint.h>

enum asm_riscv_encoding_type
{
	ASM_RISCV_ENCODING_R,
	ASM_RISCV_ENCODING_I,
	ASM_RISCV_ENCODING_S,
	ASM_RISCV_ENCODING_B,
	ASM_RISCV_ENCODING_U,
	ASM_RISCV_ENCODING_J,
	ASM_RISCV_ENCODING_L,
	ASM_RISCV_ENCODING_SLLI,
	ASM_RISCV_ENCODING_SRXI,
	ASM_RISCV_ENCODING_NONE,
	ASM_RISCV_ENCODING_FENCE,
	ASM_RISCV_ENCODING_CSRRXI,
	ASM_RISCV_ENCODING_AMO,
	ASM_RISCV_ENCODING_AMO_LR,
	ASM_RISCV_ENCODING_SFENCE_VMA,
	ASM_RISCV_ENCODING_FR1,
	ASM_RISCV_ENCODING_FR2,
	ASM_RISCV_ENCODING_FR3,
	ASM_RISCV_ENCODING_FFR,
	ASM_RISCV_ENCODING_FRF,
	ASM_RISCV_ENCODING_FLD,
	ASM_RISCV_ENCODING_FST,
	ASM_RISCV_ENCODING_CR,
	ASM_RISCV_ENCODING_CI,
	ASM_RISCV_ENCODING_CSS,
	ASM_RISCV_ENCODING_CIW,
	ASM_RISCV_ENCODING_CL,
	ASM_RISCV_ENCODING_CS,
	ASM_RISCV_ENCODING_CA,
	ASM_RISCV_ENCODING_CB,
	ASM_RISCV_ENCODING_CJ,
	ASM_RISCV_ENCODING_CJR,
	ASM_RISCV_ENCODING_CSLLI,
	ASM_RISCV_ENCODING_CSRXI,
	ASM_RISCV_ENCODING_BC,
};

enum asm_riscv_extension
{
	ASM_RISCV_EXT_32I,
	ASM_RISCV_EXT_64I,
	ASM_RISCV_EXT_32A,
	ASM_RISCV_EXT_64A,
	ASM_RISCV_EXT_ZIFENCEI,
	ASM_RISCV_EXT_ZICSR,
	ASM_RISCV_EXT_32M,
	ASM_RISCV_EXT_64M,
	ASM_RISCV_EXT_N,
	ASM_RISCV_EXT_F,
	ASM_RISCV_EXT_D,
	ASM_RISCV_EXT_32C,
	ASM_RISCV_EXT_64C,
	ASM_RISCV_EXT_ZBA,
	ASM_RISCV_EXT_ZBB,
	ASM_RISCV_EXT_ZBC,
	ASM_RISCV_EXT_ZBS,
};

struct asm_riscv_opcode
{
	char name[14];
	uint8_t encoding;
	uint8_t extension;
};

int asm_riscv_disas(char *buf, size_t size, const uint8_t *data, size_t pos);

#endif
