NAME    = tar
VERSION = 1.35
FILE    = $(NAME)-$(VERSION).tar.xz
HASH    = 4d62ff37342ec7aed748535323930c7cf94acf71c3591882b26a7ea50f3edc16
DIR     = $(NAME)-$(VERSION)
URL     = $(GNU_MIRROR_URL)/$(NAME)/$(FILE)

CONFIG_SUB = build-aux/config.sub

include $(MAKEDIR)/ext_tar.mk
