#include "elf_64.h"

#define ELFEM EM_RISCV

#define R_NONE         R_RISCV_NONE
#define R_RELATIVE64   R_RISCV_RELATIVE
#define R_ABS64        R_RISCV_64
#define R_TLS_DTPMOD64 R_RISCV_TLS_DTPMOD64
#define R_TLS_DTPOFF64 R_RISCV_TLS_DTPREL64
#define R_TLS_TPOFF64  R_RISCV_TLS_TPREL64
