#include "elf_64.h"

#define ELFEM EM_AARCH64

#define R_NONE         R_AARCH64_NONE
#define R_RELATIVE64   R_AARCH64_RELATIVE
#define R_JMP_SLOT64   R_AARCH64_JUMP_SLOT
#define R_GLOB_DAT64   R_AARCH64_GLOB_DAT
#define R_ABS64        R_AARCH64_ABS64
#define R_TLS_DTPMOD64 R_AARCH64_TLS_DTPMOD
#define R_TLS_DTPOFF64 R_AARCH64_TLS_DTPREL
#define R_TLS_TPOFF64  R_AARCH64_TLS_TPREL
