NAME    = gmp
VERSION = 6.3.0
FILE    = $(NAME)-$(VERSION).tar.xz
HASH    = a3c2b80201b89e68616f4ad30bc66aee4927c3ce50e33929ca819d5c43538898
DIR     = $(NAME)-$(VERSION)
URL     = $(GNU_MIRROR_URL)/$(NAME)/$(FILE)

CONFIG_SUB = config.sub
CONFIG_GUESS = config.guess

include $(MAKEDIR)/ext_tar.mk
