BIN = libfetch

SRC = fetch.c \
      url.c \
      file.c \
      http.c \

HDR = fetch.h \

LIB = libz.so \

VERSION_MAJOR = 1
VERSION_MINOR = 0
VERSION_BUILD = 0

include $(MAKEDIR)/lib.mk
