NAME    = libiconv
VERSION = 1.17
FILE    = $(NAME)-$(VERSION).tar.gz
HASH    = 8f74213b56238c85a50a5329f77e06198771e70dd9a739779f4c02f65d971313
DIR     = $(NAME)-$(VERSION)
URL     = $(GNU_MIRROR_URL)/$(NAME)/$(FILE)

CONFIG_SUB = build-aux/config.sub

include $(MAKEDIR)/ext_tar.mk
