BIN = libpthread

SRC = arch/$(ARCH)/_pthread_fork.S \
      barrier.c \
      cleanup.c \
      cond.c \
      cnd.c \
      key.c \
      mtx.c \
      mutex.c \
      once.c \
      rwlock.c \
      spin.c \
      thrd.c \
      thread.c \
      tss.c \

LIB = ld.so

VERSION_MAJOR = 1
VERSION_MINOR = 0
VERSION_BUILD = 0

include $(MAKEDIR)/lib.mk
