NAME    = texinfo
VERSION = 7.1
FILE    = $(NAME)-$(VERSION).tar.xz
HASH    = deeec9f19f159e046fdf8ad22231981806dac332cc372f1c763504ad82b30953
DIR     = $(NAME)-$(VERSION)
URL     = $(GNU_MIRROR_URL)/$(NAME)/$(FILE)

CONFIG_SUB = build-aux/config.sub

include $(MAKEDIR)/ext_tar.mk
