NAME    = grep
VERSION = 3.11
FILE    = $(NAME)-$(VERSION).tar.xz
HASH    = 1db2aedde89d0dea42b16d9528f894c8d15dae4e190b59aecc78f5a951276eab
DIR     = $(NAME)-$(VERSION)
URL     = $(GNU_MIRROR_URL)/$(NAME)/$(FILE)

CONFIG_SUB = build-aux/config.sub

include $(MAKEDIR)/ext_tar.mk
