#ifndef SYS_PTRACE_H
#define SYS_PTRACE_H

#include <sys/types.h>

#ifdef __cplusplus
extern "C" {
#endif

enum __ptrace_request
{
	PTRACE_TRACEME,
	PTRACE_PEEKTEXT,
	PTRACE_PEEKDATA,
	PTRACE_PEEKUSER,
	PTRACE_POKETEXT,
	PTRACE_POKEDATA,
	PTRACE_POKEUSER,
	PTRACE_GETREGS,
	PTRACE_GETFPREGS,
	PTRACE_SETREGS,
	PTRACE_SETFPREGS,
	PTRACE_CONT,
	PTRACE_SYSCALL,
	PTRACE_SINGLESTEP,
	PTRACE_KILL,
	PTRACE_ATTACH,
	PTRACE_DETACH,
	PTRACE_SEIZE,
	PTRACE_LISTEN,
	PTRACE_GETSIGINFO,
	PTRACE_SETOPTIONS,
	PTRACE_GET_THREAD_AREA,
	PTRACE_SET_THREAD_AREA,
	PTRACE_GETSIGMASK,
	PTRACE_SETSIGMASK,
};

#define PTRACE_O_TRACESYSGOOD (1 << 0)
#define PTRACE_O_EXITKILL     (1 << 1)
#define PTRACE_O_TRACECLONE   (1 << 2)
#define PTRACE_O_TRACEFORK    (1 << 3)
#define PTRACE_O_TRACEVFORK   (1 << 4)

#define PTRACE_EVENT_CLONE 1
#define PTRACE_EVENT_FORK  2
#define PTRACE_EVENT_VFORK 3

long ptrace(enum __ptrace_request request, ...);

#ifdef __cplusplus
}
#endif

#endif
