NAME    = patch
VERSION = 2.7.6
FILE    = $(NAME)-$(VERSION).tar.xz
HASH    = ac610bda97abe0d9f6b7c963255a11dcb196c25e337c61f94e4778d632f1d8fd
DIR     = $(NAME)-$(VERSION)
URL     = $(GNU_MIRROR_URL)/$(NAME)/$(FILE)

CONFIG_SUB = build-aux/config.sub

include $(MAKEDIR)/ext_tar.mk
