include $(MAKEDIR)/env.mk

DIRS = ld \
       libc \
       libm \
       libdl \
       libreadline \
       libhistory \
       libz \
       libpng \
       libutil \
       libfetch \
       libpthread \
       libdbg \
       libelf \
       libjpeg \
       libh261 \
       libasm \

include $(MAKEDIR)/dir.mk
