NAME    = mpc
VERSION = 1.3.1
FILE    = $(NAME)-$(VERSION).tar.gz
HASH    = ab642492f5cf882b74aa0cb730cd410a81edcdbec895183ce930e706c1c759b8
DIR     = $(NAME)-$(VERSION)
URL     = $(GNU_MIRROR_URL)/$(NAME)/$(FILE)

CONFIG_SUB = build-aux/config.sub

include $(MAKEDIR)/ext_tar.mk
