NAME    = bash
VERSION = 5.2.15
FILE    = $(NAME)-$(VERSION).tar.gz
HASH    = 13720965b5f4fc3a0d4b61dd37e7565c741da9a5be24edc2ae00182fc1b3588c
DIR     = $(NAME)-$(VERSION)
URL     = $(GNU_MIRROR_URL)/$(NAME)/$(FILE)

CONFIG_SUB = support/config.sub

include $(MAKEDIR)/ext_tar.mk
