BIN = libz

SRC = inflate.c \
      gzip.c \
      adler32.c \
      crc32.c \
      huffman.c \
      deflate.c \

HDR = zlib.h \

VERSION_MAJOR = 1
VERSION_MINOR = 0
VERSION_BUILD = 0

include $(MAKEDIR)/lib.mk
