NAME    = diffutils
VERSION = 3.10
FILE    = $(NAME)-$(VERSION).tar.xz
HASH    = 90e5e93cc724e4ebe12ede80df1634063c7a855692685919bfe60b556c9bd09e
DIR     = $(NAME)-$(VERSION)
URL     = $(GNU_MIRROR_URL)/$(NAME)/$(FILE)

CONFIG_SUB = build-aux/config.sub

include $(MAKEDIR)/ext_tar.mk
