NAME    = sed
VERSION = 4.9
FILE    = $(NAME)-$(VERSION).tar.xz
HASH    = 6e226b732e1cd739464ad6862bd1a1aba42d7982922da7a53519631d24975181
DIR     = $(NAME)-$(VERSION)
URL     = $(GNU_MIRROR_URL)/$(NAME)/$(FILE)

CONFIG_SUB = build-aux/config.sub

include $(MAKEDIR)/ext_tar.mk
