NAME    = gdb
VERSION = 14.2
FILE    = $(NAME)-$(VERSION).tar.xz
HASH    = 2d4dd8061d8ded12b6c63f55e45344881e8226105f4d2a9b234040efa5ce7772
DIR     = $(NAME)-$(VERSION)
URL     = $(GNU_MIRROR_URL)/$(NAME)/$(FILE)

CONFIG_SUB = config.sub

include $(MAKEDIR)/ext_tar.mk
