NAME    = gettext
VERSION = 0.22.4
FILE    = $(NAME)-$(VERSION).tar.xz
HASH    = 29217f1816ee2e777fa9a01f9956a14139c0c23cc1b20368f06b2888e8a34116
DIR     = $(NAME)-$(VERSION)
URL     = $(GNU_MIRROR_URL)/$(NAME)/$(FILE)

CONFIGURE_ARGS = --disable-nls

CONFIG_SUB = build-aux/config.sub

include $(MAKEDIR)/ext_tar.mk
