NAME    = findutils
VERSION = 4.9.0
FILE    = $(NAME)-$(VERSION).tar.xz
HASH    = a2bfb8c09d436770edc59f50fa483e785b161a3b7b9d547573cb08065fd462fe
DIR     = $(NAME)-$(VERSION)
URL     = $(GNU_MIRROR_URL)/$(NAME)/$(FILE)

CONFIG_SUB = build-aux/config.sub

include $(MAKEDIR)/ext_tar.mk
