NAME    = xz
VERSION = 5.4.5
FILE    = $(NAME)-$(VERSION).tar.xz
HASH    = da9dec6c12cf2ecf269c31ab65b5de18e8e52b96f35d5bcd08c12b43e6878803
DIR     = $(NAME)-$(VERSION)
URL     = https://github.com/tukaani-project/xz/releases/download/v$(VERSION)/$(FILE)

CONFIG_SUB = build-aux/config.sub

include $(MAKEDIR)/ext_tar.mk
